# Generated by Django 2.2.5 on 2019-09-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localities', '0002_auto_20190920_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='short_name',
            new_name='attr_name',
        ),
        migrations.AddField(
            model_name='city',
            name='attr_name',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='locality',
            name='attr_name',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='sublocality',
            name='attr_name',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
