# Generated by Django 2.2.5 on 2019-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='popularity',
            field=models.CharField(choices=[('LT', 'Lowest'), ('LW', 'Low'), ('MD', 'Medium'), ('HI', 'High'), ('HT', 'Highest')], default='MD', max_length=2),
        ),
    ]
