# Generated by Django 2.2.5 on 2019-09-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0002_auto_20190920_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attr_name',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='attr_name',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
