# Generated by Django 2.2.5 on 2019-09-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('amount_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localities.City')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.Category')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localities.Locality')),
                ('sub_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.SubCategory')),
            ],
        ),
    ]
