# Generated by Django 2.2.5 on 2019-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityrate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
