# Generated by Django 2.2.5 on 2019-09-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationclass',
            name='rate',
        ),
    ]
