# Generated by Django 2.2.5 on 2019-09-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_remove_stationclass_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='water_mark',
        ),
    ]
