# Generated by Django 2.2.5 on 2019-09-12 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GST and other charges', max_digits=8),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='footer_file',
            field=models.FileField(upload_to='campaigns/footer_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
