# Generated by Django 2.2.5 on 2019-09-04 17:03

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='unique_id',
            field=models.CharField(blank=True, default=campaigns.models.unique_id_generator, max_length=64),
        ),
    ]
