# Generated by Django 2.2.5 on 2019-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20190904_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='default_font',
            field=models.CharField(blank=True, choices=[('AR', 'Arial'), ('CL', 'Calibari'), ('HL', 'Halvetica'), ('TR', 'Times Roman')], max_length=4),
        ),
        migrations.AlterField(
            model_name='entity',
            name='default_font_size',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
